version: '3'

networks:
        es:
                driver: bridge

services:
        kibana:
                image: kibana:7.10.1
                container_name: kibana7.10.1
                restart: always
                environment:
                        SERVER_NAME: kibana7.10.1
                        ELASTICSEARCH_HOSTS: '["http://es:9200"]'
                networks:
                        - es
                ports:
                        - ${KIBANA_PORT-5601}:${KIBANA_PORT-5601}
