version: '3'
services:
        mysql:
                image: mysql:8.0.23
                container_name: mysql8.0.23
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                ports:
                        - ${MYSQL_PORT-3306}:${MYSQL_PORT-3306}
                environment:
                        MYSQL_ROOT_PASSWORD: 123456
                volumes:
                        - /export/data/mysql:/var/lib/mysql
                tty: true